name: beamify_creator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-210.4.beta <4.0.0"

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.15.8
  device_preview: ^1.1.0
  file_picker: ^8.0.0+1
  firebase_core: ^2.25.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_facebook_auth: ^6.0.4
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_webrtc: ^0.9.47
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  pinput: ^3.0.1
  socket_io_client: ^2.0.3+1
  firebase_core: ^2.25.1
  cloud_firestore: ^4.15.8
  audio_session: ^0.1.19

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
