name: beamify_creator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  http: ^1.2.0
  pinput: ^3.0.1
  flutter_secure_storage: ^9.0.0
  device_preview: ^1.1.0
  google_fonts: 6.1.0
  flutter_webrtc: ^0.9.47
  socket_io_client: ^2.0.3+1
  firebase_core: ^2.25.1
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - assets/icons/
  - assets/images/onboarding_1.png
  - assets/images/onboarding_2.png
